Andreea/library/core/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

from my_auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('library.urls')),
    url(r'^auth/', include('my_auth.urls'))
]

Andreea/library/library/urls.py
from django.conf.urls import url

from library import views

app_name = 'library'


urlpatterns = [
    url(r'^library/', views.BorrowBooksList.as_view(), name='library'),
    url(r'^my-books/', views.MyBooks.as_view(), name='my-books'),
    url(r'^welcome/', views.index, name='home'),
]

Andreea/library/my_auth/urls.py
from django.conf.urls import url
from my_auth import views

app_name = 'my_auth'


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout')
]

Andreea/library/library/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Books(models.Model):
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    genre = models.CharField(max_length=150)
    pub_date = models.DateField()
    availability = models.BooleanField(default=True)
    book_queue = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.title


class BorrowedBooks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + '. User: "' + str(self.user.username) + '" Book : "' + str(self.book) + '"'

Andreea/library/my_auth/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserProfileInfo(models.Model):

    ONE_MONTH, SIX_MONTH = ('one_month', 'six_month')
    SUBSCRIPTION_CHOICES = (
        (ONE_MONTH, 'One Month'),
        (SIX_MONTH, 'Six Months'),
    )

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    payment_type = models.CharField(choices=SUBSCRIPTION_CHOICES, max_length=100, default=ONE_MONTH, verbose_name='Subscription Type')

    def __str__(self):
        return self.user.username

Andreea/library/library/forms.py
from django import forms
from . import models

class AddBorrowedBook(forms.ModelForm):
    class Meta:
        model = models.BorrowedBooks
        fields = ['Borrow']


class MyBooks(forms.ModelForm):
    class Meta:
        model = models.BorrowedBooks

Andreea/library/my_auth/forms.py
from django import forms
from django.contrib.auth.models import User

from my_auth.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password',)


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('payment_type', )

Andreea/library/library/views.py
import datetime

from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView
from .utiles import *

from .models import Books, BorrowedBooks

mediator = Mediator()

def index(request):
    if request.user.is_authenticated:
        return render(request, 'welcomePage.html')
    else:
        return redirect('/auth/login/')


class BorrowBooksList(View):
    def get(self, request, *args, **kwargs):
        books = Books.objects.all()

        filter_query = request.GET.get('filter', None)
        type_query = request.GET.get('type', None)
        if not filter_query:
            return render(request, "Library.html", {'books_list': books})
        else:
            if type_query == 'genre':
                try:
                    req = RequestMyBooksGenreHandle
                    return mediator.mediate(req)
                except Exception as e:
                    return render(request, "Library.html", {'error': True})
            elif type_query == 'pub_date':
                try:
                    req = RequestMyBooksPubDateHandle
                    return mediator.mediate(req)
                except Exception as e:
                    return render(request, "Library.html", {'error': True})

    def post(self, request, *args, **kwargs):
        book_id = request.POST.get('book_id', None)
        if not book_id:
            return render(request, 'Library.html', {'error': True})
        else:
            book = Books.objects.get(pk=book_id)
            if book.availability:
                req = AvailableBooksHandle
                return mediator.mediate(req)
            else:
                book.book_queue += str(request.user.id) + ';'
                book.save()
                return render(request, 'Library.html', {'queue_added': True})


class MyBooks(View):
    def get(self, request, *args, **kwargs):
        book_list = BorrowedBooks.objects.filter(user=request.user)
        if not book_list:
            return render(request, "myBooks.html", {'no_borrowed': True})
        book_list = [item.book for item in book_list]
        context = {
            'book_list': book_list
        }
        return render(request, "myBooks.html", context=context)

    def post(self, request, *args, **kwargs):
        book_id = request.POST.get('book_id', None)
        if not book_id:
            return render(request, "myBooks.html", {'error': True})
        book = Books.objects.get(pk=book_id)
        book_borrowed = BorrowedBooks.objects.filter(user=request.user, book=book)
        book_borrowed.delete()
        queue = list(filter(None, book.book_queue.split(';')))
        if len(queue) > 0:
            req = MyBooksHandle
            return mediator.mediate(req)
        elif not len(queue):
            book.book_queue = ''
            book.availability = True
            book.save()
            book_borrowed.delete()
            return render(request, "myBooks.html", {'success': True})
        else:
            return render(request, "myBooks.html", {'error': True})

Andreea/library/my_auth/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from my_auth.forms import UserForm, UserProfileInfoForm


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'registerForm.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/welcome/')
            else:
                return render(request, 'index.html',
                              {
                                  'invalid_credential': True,
                                  'invalid_message': 'Your account is inactive.'
                              })
        else:
            return render(request, 'index.html',
                          {
                            'invalid_credential': True,
                            'invalid_message': 'Invalid login details given'
                          })
    else:
        return render(request, 'index.html', {})

Andreea/library/templates/Library.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
    <style>
        .special-filter {
            border: 1px solid #ccc;
            box-shadow: 1px 0 3px rgba(0, 0, 0, 0.1);
            display: inline;
            background-color: darkgrey;
            border-radius: 10px;
            padding: 10px
        }
    </style>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b> BRAND</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar10">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar10">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="/library/">Library</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/my-books">My books</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/welcome">First page</a> </li>
          <li class="nav-item"> <a class="nav-link" href={% url 'my_auth:user_logout' %}>Log out</a> </li>
        </ul> <a class="btn navbar-btn ml-md-2 btn-light text-dark">Contact us</a>
      </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Genre</button>
            <div class="dropdown-menu">
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/library/?filter=thriller&type=genre">Thriller</a>
                <a class="dropdown-item" href="/library/?filter=romance&type=genre">Romance</a>
                <a class="dropdown-item" href="/library/?filter=comedy&type=genre">Comedy</a>
                <a class="dropdown-item" href="/library/?filter=drama&type=genre">Drama</a>
            </div>
          </div>
          <div class="btn-group">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Publication Date</button>
            <div class="dropdown-menu">
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/library/?filter=most&type=pub_date">Most Recent</a>
                <a class="dropdown-item" href="/library/?filter=old&type=pub_date">Old</a>
            </div>
          </div>
          <div class="btn-group">
            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Popular</button>
            <div class="dropdown-menu">
              <div class="dropdown-divider"></div>
              <span class="dropdown-item-text">Most borrowed</span>
            </div>
          </div>
            <div class="btn-group">
                <button class="btn btn-danger"><a style="color: white" href="/library/">All Books</a></button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="">
        {% if error %}<h1 style="color: #e4606d">Something went terribly wrong! Please try again later</h1>{% endif %}
        {% if success %}<h1 style="color: #1e7e34">The book was borrowed, congrats!</h1>{% endif %}
        {% if queue_added %}<h1>The book was added in the waiting queue</h1>{% endif %}
        {% if is_filtered_applied %} <h3 class="special-filter">Applied filter: {{ filter }}</h3> {% endif %}
          <div class="table-responsive">
            <table class="table table-bordered ">
              <thead class="thead-dark">
                <tr>
                  <th>#</th>
                  <th>Title</th>
                  <th>Author</th>
                  <th>Genre</th>
                  <th>Publication Date</th>
                  <th>Availability</th>
                </tr>
              </thead>
              <tbody>

              {% for book in books_list %}
                <tr>
                  <th scope="row">{{ book.id }}</th>
                  <td>{{ book.title }}</td>
                  <td>{{ book.author }}</td>
                  <td>{{ book.genre }}</td>
                  <td>{{ book.pub_date }}</td>
                  <td>{{ book.availability }}</td>
                  <td style="border: none">
                      <form method="post">
                          {% csrf_token %}
                          <input type="hidden" value="{{ book.id }}" name="book_id">
                          {% if book.availability %}<button class="btn btn-primary" type="submit">Borrow book</button>
                          {% else %}<button class="btn btn-primary" type="submit">Add waiting queue</button>
                          {% endif %}
                      </form>
                  </td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

Andreea/library/templates/RegisterRequests.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b> BRAND</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar10">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar10">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="RegisterRequests.html">Register Requests</a> </li>
          <li class="nav-item"> <a class="nav-link" href="Returns.html">Returns</a> </li>
          <li class="nav-item"> <a class="nav-link" href="addBooks.html">Add books</a> </li>
          <li class="nav-item"> <a class="nav-link" href="#">Log out</a> </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="table-responsive">
            <table class="table table-bordered ">
              <thead class="thead-dark">
                <tr>
                  <th>#</th>
                  <th>User name</th>
                  <th>Type of payment</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>1</th>
                  <td>Mark</td>
                  <td>Otto</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td>Jacob</td>
                  <td>Thornton</td>
                </tr>
                <tr>
                  <th scope="row">3</th>
                  <td>Larry</td>
                  <td>the Bird</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="">
            <div class="form-group"> <label>User id</label> <input type="number" class="form-control" placeholder="ID"> </div>
            <button type="submit" class="btn btn-primary">OK</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>
</body>

</html>

Andreea/library/templates/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body style="background-color: #f3f3f3">
  <nav class="navbar navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-circle"></i>
        <b style=""> BRAND</b>
      </a> </div>
  </nav>
  <div class="py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="p-5 col-md-7 d-flex flex-column justify-content-center" style="">
          <h3 class="display-4 mb-3">YOUR LIBRARY</h3>
          <p class="mb-4 lead">Log in or register and find your soul book</p>
        </div>
        <div class="p-5 col-md-5" style="">
          <h3 class="mb-3">Log in</h3>
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input
                    class="form-control"
                    placeholder="Type here"
                    name="username"
                    type="text"
                    id="username"
                >
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input
                    type="password"
                    class="form-control"
                    placeholder="password"
                    name="password"
                    id="password"
                >
            </div>
              {% if invalid_credential %}
                <span style="color: red">{{ invalid_message }}</span>
              {% endif %}
              <button type="submit" class="btn mt-4 btn-block btn-outline-dark p-2"><b>Log in</b></button>
          </form>
        <button class="btn mt-4 btn-block btn-outline-dark p-2"><a href="/auth/register">Register</a></button>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

Andreea/library/templates/myBooks.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b> BRAND</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar10">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar10">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="/library/">Library</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/my-books">My books</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/welcome">First page</a> </li>
          <li class="nav-item"> <a class="nav-link" href={% url 'my_auth:user_logout' %}>Log out</a> </li>
        </ul> <a class="btn navbar-btn ml-md-2 btn-light text-dark">Contact us</a>
      </div>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
            {% if error %}<h1 style="color: #e4606d">Something went terribly wrong! Please try again later</h1>{% endif %}
            {% if success %}<h1 style="color: #1e7e34">The book was eliminated, congrats!</h1>{% endif %}
          <div class="table-responsive">
            <table class="table table-bordered ">
              <thead class="thead-dark">
                <tr>
                  <th>#</th>
                  <th>Title</th>
                  <th>Author</th>
                  <th>Genre</th>
                  <th>Publication Date</th>
                  <th>Availability</th>
                </tr>
              </thead>
              <tbody>

                {% for book in book_list %}
                <tr>
                  <th scope="row">{{ book.id }}</th>
                  <td>{{ book.title }}</td>
                  <td>{{ book.author }}</td>
                  <td>{{ book.genre }}</td>
                  <td>{{ book.pub_date }}</td>
                  <td>{{ book.availability }}</td>
                    <td style="border: none">
                      <form method="post">
                          {% csrf_token %}
                          <input type="hidden" value="{{ book.id }}" name="book_id">
                          <button class="btn btn-danger" type="submit">Release Book</button>
                      </form>
                  </td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 20px;right:20px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:220px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;<img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16"></pingendo>
</body>

</html>

Andreea/library/templates/welcomePage.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://static.pingendo.com/bootstrap/bootstrap-4.3.1.css">
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container"> <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-stop-circle"></i>
        <b> BRAND</b>
      </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar10">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar10">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"> <a class="nav-link" href="/library/">Library</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/my-books">My books</a> </li>
          <li class="nav-item"> <a class="nav-link" href="/welcome">First page</a> </li>
          <li class="nav-item"> <a class="nav-link" href={% url 'my_auth:user_logout' %}>Log out</a> </li>
        </ul> <a class="btn navbar-btn ml-md-2 btn-light text-dark">Contact us</a>
      </div>
    </div>
  </nav>
  <div class="py-5 text-center text-white h-100 align-items-center d-flex" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, .75), rgba(0, 0, 0, .75)), url(https://static.pingendo.com/cover-bubble-dark.svg);  background-position: center center, center center;  background-size: cover, cover;  background-repeat: repeat, repeat;">
    <div class="container py-5">
      <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">
          <h1 class="display-3 mb-4">WELCOME BACK</h1>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>